{
	'name': 'Security Guards Payroll System',
	'version': '0.1',
	'category': 'SOS',
	'license': 'AGPL-3',
	'description': "This module manages the Guards Salaries",
	'author': 'Farooq',
	'website': 'http://www.aarsolerp.com/',
	'depends': ['base','hr','account','sos','hr_payroll'],
	'init_xml': [],
	'data': [
		'security/ir.model.access.csv',
		'security/security.xml',
		'menu/menu.xml',

		'views/sos_attendance_view.xml',
		'views/sos_shortfall_view.xml',
		'views/sos_replacement_view.xml',
		'views/report_gcontributionregister.xml',
		'views/guards_payroll_view.xml',
		'views/guards_payroll_run_view.xml',
		# 'views/guards_payroll_workflow.xml',
		'views/guards_arrears_view.xml',
		'views/guards_payslip_cron_view.xml',
		'views/guards_payslip_audit_view.xml',
		'views/sos_attendance_log_view.xml',
		'views/project_salary_pending_view.xml',
		# 'views/sos_payroll_cron.xml',
      	
		'views/report_ablincentive.xml',
		'views/abl_incentive_report.xml',
		'views/sos_attendance_close_view.xml',
		'views/sos_attendance1_view.xml',
		'views/sos_pss_attendance_view.xml',
		'views/guards_salary_difference_view.xml',
		'views/report_securitydeposit.xml',
		'views/report_mbldeduction.xml',
		'views/report_poststotalattendance.xml',
		'views/report_guardsnocontract.xml',
		'views/report_guardsalary.xml',
		'views/report_audit_guardsalary.xml',
		'views/report_salary_advisedpost.xml',
		'views/report_salary_advisedcenter.xml',
		'views/report_salary_advisedbase.xml',
		'views/report_new_guardsalary.xml',

		
		'views/sos_staff_attendance_view.xml',
		
		'wizard/rep_guards_salary_wizard_view.xml',
#		'wizard/rep_guards_yearly_salary_detail_view.xml',
		'wizard/rep_hr_salary_headoffice_view.xml',
		'wizard/rep_hr_salary_regions_view.xml',
		'wizard/rep_salary_advised_view.xml',
		'wizard/guards_payroll_payslips_by_employees.xml',
#		'wizard/guards_payroll_contribution_register_report.xml',
		'wizard/guards_payroll_payslips_by_runs.xml',

		'wizard/payroll_states_view.xml',        
		'wizard/guards_payslips_done_view.xml',
		'wizard/slip_process_view.xml',		
		'wizard/guards_payslips_cron_wizard_view.xml',
		'wizard/salary_stop_wizard_view.xml',

		'wizard/attendance/guards_attendance_mark_view.xml',
		'wizard/attendance/guards_extra_attendance_mark_view.xml',
		'wizard/attendance/rep_guards_attendance_register_wizard_view.xml',
		'wizard/attendance/rep_guards_attendance_wizard_view.xml',
		'wizard/attendance/rep_guards_consolidated_attendance_wizard_view.xml',		
		'wizard/attendance/rep_guards_daily_absent_wizard_view.xml',
		'wizard/attendance/rep_guards_daily_attendance_wizard_view.xml',
		'wizard/attendance/rep_guards_shortfall_wizard_view.xml',
		'wizard/attendance/pss_attendance_summary_wizard_view.xml',
		'wizard/attendance/rep_pss_attendance_wizard_view.xml',
				
		'wizard/attendance/rep_posts_attendance_register_wizard_view.xml',
		'wizard/attendance/rep_posts_total_attendance_view.xml',
		'wizard/attendance/guards_attendance_date_setting_view.xml',
		'wizard/staff/staff_payslips_cron_wizard_view.xml',
		'wizard/abl_incentive_wizard_view.xml',
		'wizard/rep_guards_security_deposit_view.xml',
		'wizard/rep_guards_mbl_deduction_view.xml',
		'wizard/guard_payslip_draft_wizard_view.xml',
		'wizard/guards_no_contract_wizard_view.xml',
		
		'wizard/staff/calculate_month_attendance_view.xml',
		'wizard/staff/staff_arrears_wizard_view.xml',
		
		'report/attendance/report_guardattendance.xml',
		'report/attendance/report_postsattendance_register.xml',
		'report/attendance/report_guardsattendance_register.xml',
		'report/attendance/report_shortfallcenter.xml',
		'report/attendance/report_shortfallproject.xml',
		'report/attendance/report_shortfallpost.xml',
		'report/attendance/report_guards_consolidatedattendance.xml',
#		'report/attendance/sos_device_attendance_report_view.xml',
        'report/attendance/report_pssattendance_summary.xml',
        'report/attendance/report_pssattendance.xml',
        
        #Advices Wizard
		'wizard/advices/guards_salary_advise_view.xml',
		'wizard/advices/guards_payroll_advice_summary_view.xml',
		'wizard/advices/mbl_salary_advise_view.xml',
		'wizard/advices/projects_salary_advise_view.xml',
		'wizard/advices/exit_form_salary_advise_view.xml',
		'wizard/advices/rep_guards_subadvice_salary_view.xml',
      
      
        #Advices Reports
        'report/advices/report.xml',
        'report/advices/guards_payroll_advice_report.xml',
        'report/advices/guards_payroll_advice_summary_report.xml',
        'report/advices/report_projectssalary_advice.xml',
        'report/advices/guards_subadvice_salary_report.xml',


		'report/report.xml',
		'report/attendance/report.xml',
		'menu/sos_menu.xml',
		
	],
	'demo_xml': [],
	'installable': True,
	'application' : True,
}
