from . import daily_stock_wizard
from . import uniform_wizard
from . import shoes_wizard
from . import accessories_wizard 
from . import weapon_wizard
from . import ammunition_wizard
from . import stationary_wizard
from . import lady_uniform_wizard
from . import trouser_wizard
from . import tshirt_wizard
