{
	'name': 'Security Guards System',
	'version': '0.1',
	'category': 'Security Guards System',
	'license': 'AGPL-3',
	'description': "This module manages the Guards data and their Salaries",
	'author': 'Farooq',
	'website': 'http://www.aarsolerp.com/',
	'depends': ['hr','hr_contract','base'],
	'init_xml': [],
	'data': [
		
		'data/sos_data.xml',
		'security/ir.model.access.csv',
		'security/sos_security.xml',
        
		'views/guard_view.xml',
		'views/post_center_project_view.xml',
		'views/sos_view.xml',
		'views/period_view.xml',
		'views/clients_visit_view.xml',
		'views/armourer_visit_view.xml',
		'views/sos_attendance_device_view.xml',
		'views/employee_rfid_view.xml',
		'views/sos_weapon_view.xml',
		'views/sos_weapon_post_view.xml',
		'views/black_listed_guards_view.xml',
		'views/account_info_log_view.xml',
		'views/report_bankaccounts.xml',
	#	'views/hr_employee_cron.xml',
		'views/sos_hr_contract_ext_view.xml',
		'views/sos_rejoin_guards_view.xml',
		
		'views/report_guards_jointermination.xml',
		'views/report_posts_jointermination.xml',
		'views/report_projectguard_details.xml',
		'views/report_project_postwiseguard_details.xml',
		'views/report_center_postwiseguard_details.xml',
		'views/report_guardsdata.xml',
		'views/weapon_posting_wizard.xml',
		'views/weapon_repairing_wizard.xml',
		'views/sos_weapon_status_wizard_view.xml',
		'views/weapon_terminate_wizard.xml',
		'views/sos_guards_exit_form_view.xml',
		'views/sos_guards_account_block_view.xml',
		'views/sim_allotment_view.xml',
		
		'wizard/hr_guard_posting.xml',
		'wizard/guards_join_termination_view.xml',
		'wizard/posts_join_termination_view.xml',
		'wizard/guards_data_report_view.xml',
		
		'wizard/sos_staff_termination_wizard_view.xml',
		'wizard/sos_staff_attendance_wizard_view.xml',
		'wizard/sos_staff_salary_sheet_view.xml',
		'wizard/sos_guard_document_view.xml',
		'wizard/sos_guard_status_wizard_view.xml',
		'wizard/sos_staff_gross_salary_sheet_view.xml',
		'wizard/sos_staff_transfer_wizard_view.xml',
		
		'wizard/guards_bank_account_view.xml',
		'wizard/sos_appointment_wizard_view.xml',
		'wizard/sos_project_guards_wizard_view.xml',
		'wizard/sos_project_postwise_guards_wizard_view.xml',
		'wizard/sos_center_postwise_guards_wizard_view.xml',
		'wizard/guards_docs_complaint_wizard_view.xml',
		
		'wizard/daily_clients_visit_view.xml',
		'wizard/daily_armourer_visit_view.xml',
		'wizard/sos_posts_rep_wizard_view.xml',
		
		'wizard/configuration/sos_guard_multi_step_profile_view.xml',

		'report/guard_report.xml',
		'report/report_guardprofile.xml',
		'report/report_staffsalarysheet.xml',
		'report/report_guarddocument.xml',
		'report/report_guards_project.xml',
		'report/report_guards_insurance.xml',
		'report/report_projects_salaryrates.xml',
		'report/report_projects_invoicerates.xml',
		'report/report_centers_salaryrates.xml',
		'report/report_centers_invoicerates.xml',
		'report/report_guards_docscomplaint.xml',
		
		'report/report_clientsvisit.xml',
		'report/report_armourervisit.xml',
		'report/report_postsaddress.xml',
		'report/report_guards_appointmentletter.xml',
		'report/report_guards_exitform.xml',
		'report/report_policeverification.xml',
		'report/report_guards_exitform2.xml',
		
		'report/report_staff_gross_salarysheet.xml',
		'report/staff_payment_advice_report.xml',
	
		'report/report.xml',       
		'menu/sos_menu.xml',
	],
	'demo_xml': [],
	'installable': True,
	'application' : True,
}


